import type { CSSProperties } from 'react';
import type { ThemeConfig } from 'antd';

export const colorPalette = {
  canvas: '#f7f9fb',
  surface: '#ffffff',
  surfaceSelected: '#f1f5f9',
  subtle: '#f1f5f9',
  text: '#1c1c1a',
  textSecondary: '#4a4844',
  muted: '#5e5b54',
  textDisabled: '#94a3b8',
  border: '#e2e8f0',
  borderHover: '#cbd5e1',
  borderDecorative: '#e2e8f0',
  control: '#cbd5e1',
  primary: '#1a4dc7',
  primaryHover: '#163fa4',
  primaryDark: '#163fa4',
  link: '#163fa4',
  linkHover: '#1a4dc7',
  onPrimary: '#ffffff',
  sidebar: '#1f1e1c',
  sidebarBorder: '#2e2c29',
  sidebarSelected: '#2e2c29',
  sidebarText: '#f7f5f0',
  sidebarMuted: '#b0ada6',
  baseWhite: '#ffffff',
  dataQuota: '#4c4944',
  infoSurface: '#eef4ff',
  infoBorder: '#cbd5e1',
  infoText: '#163fa4',
  successSurface: '#e7f4ec',
  successBorder: '#a9d9bc',
  successText: '#1f6f46',
  warningSurface: '#fbf0d6',
  warningBorder: '#e8c468',
  warningText: '#7a5200',
  errorSurface: '#fbeaea',
  errorBorder: '#e7acac',
  errorText: '#9b2226',
  realtimeSurface: '#e3f3f3',
  realtimeBorder: '#a8d6d8',
  realtimeText: '#146670',
  moduleSurface: '#f2eaf3',
  moduleBorder: '#d9bddc',
  moduleText: '#71447a',
  neutralSurface: '#edebe5',
  neutralBorder: '#b0ada6',
  neutralText: '#4a4844',
  commerceSurface: '#f4e9e5',
  commerceBorder: '#d9bcb1',
  commerceText: '#744638',
} as const;

type CssVariableName = `--${string}`;
type ThemeCssVariables = CSSProperties & Record<CssVariableName, string>;

export const themeCssVariables: ThemeCssVariables = {
  '--canvas': colorPalette.canvas,
  '--surface': colorPalette.surface,
  '--surface-selected': colorPalette.surfaceSelected,
  '--bg-subtle': colorPalette.subtle,
  '--subtle': colorPalette.subtle,
  '--text': colorPalette.text,
  '--text-secondary': colorPalette.textSecondary,
  '--muted': colorPalette.muted,
  '--text-disabled': colorPalette.textDisabled,
  '--border': colorPalette.border,
  '--border-hover': colorPalette.borderHover,
  '--border-decorative': colorPalette.borderDecorative,
  '--control': colorPalette.control,
  '--control-hover': colorPalette.borderHover,
  '--primary': colorPalette.primary,
  '--primary-hover': colorPalette.primaryHover,
  '--primary-dark': colorPalette.primaryDark,
  '--link': colorPalette.link,
  '--link-hover': colorPalette.linkHover,
  '--on-primary': colorPalette.onPrimary,
  '--sidebar': colorPalette.sidebar,
  '--sidebar-border': colorPalette.sidebarBorder,
  '--sidebar-selected': colorPalette.sidebarSelected,
  '--sidebar-text': colorPalette.sidebarText,
  '--sidebar-muted': colorPalette.sidebarMuted,
  '--base-white': colorPalette.baseWhite,
  '--data-quota': colorPalette.dataQuota,
  '--info-surface': colorPalette.infoSurface,
  '--info-border': colorPalette.infoBorder,
  '--info-text': colorPalette.infoText,
  '--success-surface': colorPalette.successSurface,
  '--success-border': colorPalette.successBorder,
  '--success-text': colorPalette.successText,
  '--warning-surface': colorPalette.warningSurface,
  '--warning-border': colorPalette.warningBorder,
  '--warning-text': colorPalette.warningText,
  '--error-surface': colorPalette.errorSurface,
  '--error-border': colorPalette.errorBorder,
  '--error-text': colorPalette.errorText,
  '--realtime-surface': colorPalette.realtimeSurface,
  '--realtime-border': colorPalette.realtimeBorder,
  '--realtime-text': colorPalette.realtimeText,
  '--module-surface': colorPalette.moduleSurface,
  '--module-border': colorPalette.moduleBorder,
  '--module-text': colorPalette.moduleText,
  '--neutral-surface': colorPalette.neutralSurface,
  '--neutral-border': colorPalette.neutralBorder,
  '--neutral-text': colorPalette.neutralText,
  '--commerce-surface': colorPalette.commerceSurface,
  '--commerce-border': colorPalette.commerceBorder,
  '--commerce-text': colorPalette.commerceText,
};

export const themeRootCss = `:root{${Object.entries(themeCssVariables)
  .map(([name, value]) => `${name}:${String(value)}`)
  .join(';')}}`;

export const antTheme: ThemeConfig = {
  components: {
    Button: {
      defaultActiveBg: colorPalette.subtle,
      defaultActiveBorderColor: colorPalette.borderHover,
      defaultActiveColor: colorPalette.text,
      defaultBg: colorPalette.surface,
      defaultBorderColor: colorPalette.control,
      defaultColor: colorPalette.text,
      defaultHoverBg: colorPalette.subtle,
      defaultHoverBorderColor: colorPalette.borderHover,
      defaultHoverColor: colorPalette.text,
      primaryColor: colorPalette.onPrimary,
      defaultShadow: 'none',
      primaryShadow: 'none',
      controlHeight: 44,
      controlHeightLG: 48,
      controlHeightSM: 36,
    },
    Card: {
      colorBorderSecondary: colorPalette.border,
    },
    Input: {
      activeBorderColor: colorPalette.primary,
      activeShadow: '0 0 0 3px rgb(26 77 199 / 14%)',
      hoverBorderColor: colorPalette.borderHover,
      controlHeight: 44,
      controlHeightLG: 48,
      controlHeightSM: 36,
    },
    Select: {
      activeBorderColor: colorPalette.primary,
      activeOutlineColor: 'rgb(26 77 199 / 14%)',
      hoverBorderColor: colorPalette.borderHover,
      controlHeight: 44,
      controlHeightLG: 48,
    },
    Table: {
      headerBg: colorPalette.subtle,
      headerColor: colorPalette.textSecondary,
      borderColor: colorPalette.border,
      rowHoverBg: colorPalette.canvas,
    },
    Segmented: {
      itemSelectedBg: colorPalette.primary,
      itemSelectedColor: colorPalette.onPrimary,
    },
  },
  token: {
    borderRadius: 6,
    colorBgBase: colorPalette.surface,
    colorBgContainer: colorPalette.surface,
    colorBgLayout: colorPalette.canvas,
    colorBorder: colorPalette.border,
    colorBorderSecondary: colorPalette.borderDecorative,
    colorError: colorPalette.errorText,
    colorInfo: colorPalette.infoText,
    colorLink: colorPalette.link,
    colorLinkActive: colorPalette.linkHover,
    colorLinkHover: colorPalette.linkHover,
    colorPrimary: colorPalette.primary,
    colorPrimaryActive: colorPalette.primaryHover,
    colorPrimaryHover: colorPalette.primaryHover,
    colorSuccess: colorPalette.successText,
    colorText: colorPalette.text,
    colorTextDescription: colorPalette.textSecondary,
    colorTextDisabled: colorPalette.textDisabled,
    colorTextPlaceholder: colorPalette.textDisabled,
    colorTextQuaternary: colorPalette.textDisabled,
    colorTextSecondary: colorPalette.textSecondary,
    colorTextTertiary: colorPalette.muted,
    colorWarning: colorPalette.warningText,
    colorBgElevated: colorPalette.surface,
    controlOutline: 'rgb(26 77 199 / 14%)',
    fontSize: 16,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 18,
    lineHeight: 1.6,
    fontFamily: '"IBM Plex Sans Variable", "Segoe UI", sans-serif',
  },
};
