export const REDACTED_LOG_PATHS = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["x-api-key"]',
  'req.headers["x-license-key"]',
  'req.headers["x-secret-key"]',
  'req.body.password',
  'req.body.activationCode',
  'req.body.activationKey',
  'req.body.currentPassword',
  'req.body.activationSecret',
  'req.body.envelope',
  'req.body.keyMaterial',
  'req.body.privateKey',
  'req.body.passwordConfirmation',
  'req.body.rawPayload',
  'req.body.rawIpnSecret',
  'req.body.relayerKeyMaterial',
  'req.body.signature',
  'req.body.token',
  'res.headers["set-cookie"]',
] as const;
